local T = ...
local ns = require("loader").load({}, "Defaults.lua")
local p, g = ns.DEFAULTS.profile, ns.DEFAULTS.global

T.test("display defaults are the chosen values", function()
    T.eq(p.showTimer, true); T.eq(p.locked, true)
    T.eq(p.rightClickMenu, true)
    T.eq(p.pos.x, 0); T.eq(p.pos.y, -80)
    T.eq(p.scale, 1); T.eq(p.alpha, 1); T.eq(p.strata, "MEDIUM")
    T.eq(p.hideInCombat, false); T.eq(p.showWhileAway, true)
end)

T.test("appearance defaults are the chosen values", function()
    T.eq(p.showName, true); T.eq(p.namePos, "ABOVE"); T.eq(p.align, "CENTER"); T.eq(p.spacing, 2)
    T.eq(p.timeStyle, "auto"); T.eq(p.showTenths, false)
    T.eq(p.nameFont.face, "Friz Quadrata TT"); T.eq(p.nameFont.size, 12)
    T.eq(p.nameFont.outline, "NONE"); T.eq(p.nameFont.mono, false); T.eq(p.nameFont.shadow, true)
    T.eq(p.timeFont.face, "Friz Quadrata TT"); T.eq(p.timeFont.size, 22)
    T.eq(p.timeFont.outline, "OUTLINE"); T.eq(p.timeFont.mono, false); T.eq(p.timeFont.shadow, false)
    T.eq(p.colors.name.r, 1); T.eq(p.colors.name.g, 0.82); T.eq(p.colors.name.b, 0)
    T.eq(p.colors.running.r, 1); T.eq(p.colors.running.g, 1); T.eq(p.colors.running.b, 1)
    T.eq(p.colors.away.r, 0.6); T.eq(p.colors.away.g, 0.75); T.eq(p.colors.away.b, 1)
    T.eq(p.colors.final.r, 0.25); T.eq(p.colors.final.g, 1); T.eq(p.colors.final.b, 0.25)
    T.eq(p.bg.show, true); T.eq(p.bg.texture, "Solid"); T.eq(p.bg.color.r, 0); T.eq(p.bg.color.a, 0.55)
    T.eq(p.border.show, true); T.eq(p.border.texture, "Blizzard Tooltip"); T.eq(p.border.size, 14)
    T.eq(p.border.color.r, 0.8); T.eq(p.border.color.a, 0.9)
    T.eq(p.padding, 8)
end)

T.test("rule defaults match the user's answers", function()
    T.eq(p.types.party, true); T.eq(p.types.raid, true); T.eq(p.types.pvp, true)
    T.eq(p.awayMode, "count"); T.eq(p.giveUp, "ghost"); T.eq(p.graceMinutes, 15)
    T.eq(p.offline, "count"); T.eq(p.chat, true); T.eq(p.freezeSeconds, 10)
    T.eq(g.debug, false)
end)
