local T = ...
local ns = require("loader").load({}, "RouteStore.lua", "FlightTracker.lua")

local R1 = { key = "25>80", fromName = "Crossroads, The Barrens", toName = "Ratchet, The Barrens", hops = 1 }
local R3 = { key = "25>44", fromName = "Crossroads, The Barrens", toName = "Orgrimmar, Durotar", hops = 1 }

local function make(save, routes)
    local env = { routes = routes or {}, save = save or {}, lands = {}, takeoffs = 0 }
    env.store = ns.RouteStore.New(env.routes)
    env.ft = ns.FlightTracker.New(env.store, env.save, {
        onTakeoff = function() env.takeoffs = env.takeoffs + 1 end,
        onLand = function(i) env.lands[#env.lands + 1] = i end,
    })
    return env
end

local function loaded(save, routes)
    local env = make(save, routes)
    env.ft:OnLoad(0, false)
    return env
end

-- Pick at t0, take off at t0+2, first false reading at t0+2+d, confirmed 0.1 s later.
local function fly(env, route, t0, d, seq)
    env.ft:Pick(route, t0, seq or 1)
    env.ft:Reading(false, t0 + 1)
    env.ft:Reading(true, t0 + 2)
    env.ft:Reading(true, t0 + 2 + d - 1)
    env.ft:Reading(false, t0 + 2 + d)
    env.ft:Reading(false, t0 + 2 + d + 0.1)
end

T.test("first flight learns the route; the next one counts down", function()
    local env = loaded()
    fly(env, R1, 0, 52)
    T.eq(env.lands[1].reason, "learned")
    T.near(env.lands[1].duration, 52)
    T.near(env.store:Expected("25>80"), 52)
    env.ft:Pick(R1, 100, 2)
    env.ft:Reading(true, 102)
    local v = env.ft:GetView(112)
    T.eq(v.mode, "countdown")
    T.near(v.remaining, 42)
    T.eq(v.toName, "Ratchet, The Barrens")
end)

T.test("second flight reports updated with the old expected time", function()
    local env = loaded()
    fly(env, R1, 0, 52)
    fly(env, R1, 100, 54, 2)
    T.eq(env.lands[2].reason, "updated")
    T.near(env.lands[2].expectedBefore, 52)
    T.near(env.store:Expected("25>80"), 53)
end)

T.test("an unknown route shows learning", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    local v = env.ft:GetView(12)
    T.eq(v.mode, "learning")
    T.near(v.elapsed, 10)
end)

T.test("a pick without takeoff expires after 20 s; a later flight is untracked", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(false, 19)
    T.eq(env.ft:GetState(), "pending")
    env.ft:Reading(false, 21)
    T.eq(env.ft:GetState(), "idle")
    env.ft:Reading(true, 30)
    T.eq(env.ft:GetView(31).mode, "untracked")
end)

T.test("a late takeoff within the window keeps the route", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(false, 10)
    env.ft:Reading(true, 15)
    T.eq(env.ft:GetView(16).mode, "learning")
end)

T.test("a brief false blip mid-flight does not land", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    env.ft:Reading(false, 10)
    env.ft:Reading(true, 10.05)
    env.ft:Reading(false, 54)
    env.ft:Reading(false, 54.1)
    T.eq(#env.lands, 1)
    T.near(env.lands[1].duration, 52)
end)

T.test("the display holds at a landing candidate", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    env.ft:Reading(false, 20)
    T.near(env.ft:GetView(20.05).elapsed, 18)
end)

T.test("early landing, summon and short flights are not recorded", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    env.ft:EarlyLanding()
    env.ft:Reading(false, 30)
    env.ft:Reading(false, 30.1)
    T.eq(env.lands[1].reason, "early")
    env.ft:Pick(R1, 100, 2)
    env.ft:Reading(true, 102)
    env.ft:Interrupt()
    env.ft:Reading(false, 140)
    env.ft:Reading(false, 140.1)
    T.eq(env.lands[2].reason, "interrupted")
    fly(env, R1, 200, 3, 3)
    T.eq(env.lands[3].reason, "short")
    T.eq(env.store:Count(), 0)
end)

T.test("a loading screen mid-flight suspends landing and is not recorded", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    env.ft:LoadingStarted()
    env.ft:Reading(false, 20)
    env.ft:Reading(false, 25)
    T.eq(#env.lands, 0, "suspended: readings ignored")
    env.ft:LoadingEnded()
    env.ft:Reading(false, 30)
    env.ft:Reading(false, 30.1)
    T.eq(env.lands[1].reason, "interrupted")
    T.eq(env.store:Count(), 0)
end)

T.test("an untracked flight always reports untracked with no route", function()
    local env = loaded()
    env.ft:Reading(true, 5)
    env.ft:LoadingStarted()
    env.ft:LoadingEnded()
    env.ft:Reading(false, 40)
    env.ft:Reading(false, 40.1)
    T.eq(env.lands[1].reason, "untracked")
    T.eq(env.lands[1].route, nil)
    T.eq(env.lands[1].toName, nil)
end)

T.test("picks while flying are ignored", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    env.ft:Pick(R3, 10, 2)
    T.eq(env.ft:GetView(11).toName, "Ratchet, The Barrens")
end)

T.test("two different picks make the flight ambiguous; the same pick twice does not", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Pick(R3, 1, 2)
    env.ft:Reading(true, 3)
    T.eq(env.ft:GetView(4).toName, "Orgrimmar, Durotar")
    env.ft:Reading(false, 60)
    env.ft:Reading(false, 60.1)
    T.eq(env.lands[1].reason, "ambiguous")
    fly(env, R1, 100, 52, 3)
    env.ft:Pick(R1, 200, 4)
    env.ft:Pick(R1, 201, 5)
    env.ft:Reading(true, 202)
    env.ft:Reading(false, 254)
    env.ft:Reading(false, 254.1)
    T.eq(env.lands[3].reason, "updated")
end)

T.test("CancelPending, and CancelStale by sequence or by frame", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 5)
    env.ft:CancelStale(5, 0)
    T.eq(env.ft:GetState(), "pending", "same seq, same frame: kept")
    env.ft:CancelStale(6, 0)
    T.eq(env.ft:GetState(), "idle", "picked before the last close")
    env.ft:Pick(R1, 10, 7)
    env.ft:CancelStale(0, 10)
    T.eq(env.ft:GetState(), "pending", "picked in this frame (auto-taxi): kept")
    env.ft:CancelStale(0, 10.1)
    T.eq(env.ft:GetState(), "idle", "picked in an earlier frame")
    env.ft:Pick(R1, 20, 8)
    env.ft:CancelPending()
    T.eq(env.ft:GetState(), "idle")
end)

T.test("an unresolved pick cancels a pending pick and ends resuming", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:UnresolvedPick()
    T.eq(env.ft:GetState(), "idle")
    env.ft:Reading(true, 2)
    T.eq(env.ft:GetView(3).mode, "untracked", "the flight that follows is untracked")
    env.ft:UnresolvedPick()
    T.eq(env.ft:GetState(), "flying", "no effect while flying")
    local save = { flight = { route = R1, takeoff = 2, elapsed = 28, recordable = true } }
    local env2 = make(save)
    env2.ft:OnLoad(100, true)
    env2.ft:UnresolvedPick()
    T.eq(env2.ft:GetState(), "idle")
    T.eq(save.flight, nil, "a pick proves the player is on the ground")
end)

T.test("a flight map opening ends resuming, and nothing else", function()
    local save = { flight = { route = R1, takeoff = 2, elapsed = 28, recordable = true } }
    local env = make(save)
    env.ft:OnLoad(100, true)
    env.ft:EndResume()
    T.eq(env.ft:GetState(), "idle")
    T.eq(save.flight, nil, "the player is on the ground")
    env.ft:Pick(R1, 101, 1)
    env.ft:EndResume()
    T.eq(env.ft:GetState(), "pending", "a pending pick is untouched")
end)

T.test("a repeated pick of the same route restarts the takeoff window", function()
    local env = loaded()
    env.ft:Pick(R1, 0, 1)
    env.ft:Pick(R1, 15, 2)
    env.ft:Reading(false, 30)
    T.eq(env.ft:GetState(), "pending")
    env.ft:Reading(false, 35.5)
    T.eq(env.ft:GetState(), "idle")
end)

T.test("logout while pending clears the saved flight", function()
    local env = loaded({ flight = nil })
    env.save.flight = { stale = true }
    env.ft:Pick(R1, 0, 1)
    env.ft:OnUnload(1)
    T.eq(env.save.flight, nil)
end)

T.test("a reload after a clock reset keeps the elapsed time", function()
    local save = { flight = { route = R1, takeoff = 5000, elapsed = 28, recordable = true } }
    local env = make(save)
    env.ft:OnLoad(10, true)
    env.ft:Reading(true, 11)
    T.near(env.ft:GetView(12).elapsed, 29)
end)

T.test("overtime shows how far over the expected time", function()
    local env = loaded()
    fly(env, R1, 0, 52)
    env.ft:Pick(R1, 100, 2)
    env.ft:Reading(true, 102)
    local v = env.ft:GetView(162)
    T.eq(v.mode, "overtime")
    T.near(v.over, 8)
end)

T.test("readings before OnLoad are ignored", function()
    local env = make()
    env.ft:Reading(true, 1)
    T.eq(env.ft:GetState(), "idle")
end)

T.test("/reload mid-flight resumes with the same takeoff and still records", function()
    local routes, save = {}, {}
    local env = loaded(save, routes)
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    env.ft:OnUnload(30)
    T.near(save.flight.elapsed, 28)
    local env2 = make(save, routes)
    env2.ft:OnLoad(31, true)
    T.eq(env2.ft:GetState(), "resuming")
    env2.ft:Reading(true, 32)
    T.near(env2.ft:GetView(40).elapsed, 38)
    env2.ft:Reading(false, 54)
    env2.ft:Reading(false, 54.1)
    T.eq(env2.lands[1].reason, "learned")
    T.near(env2.lands[1].duration, 52)
    T.eq(save.flight, nil)
end)

T.test("a relog mid-flight excludes offline time and is not recorded", function()
    local routes, save = {}, {}
    local env = loaded(save, routes)
    env.ft:Pick(R1, 0, 1)
    env.ft:Reading(true, 2)
    env.ft:OnUnload(30)
    local env2 = make(save, routes)
    env2.ft:OnLoad(500, false)
    env2.ft:Reading(true, 505)
    T.near(env2.ft:GetView(510).elapsed, 33)
    env2.ft:Reading(false, 529)
    env2.ft:Reading(false, 529.1)
    T.eq(env2.lands[1].reason, "relog")
    T.near(env2.lands[1].duration, 52)
    T.eq(env2.store:Count(), 0)
end)

T.test("the resume window starts at the first permitted reading", function()
    local save = { flight = { route = R1, takeoff = 2, elapsed = 28, recordable = true } }
    local env = make(save)
    env.ft:OnLoad(100, true)
    env.ft:Reading(false, 200)
    env.ft:Reading(false, 209)
    T.eq(env.ft:GetState(), "resuming")
    env.ft:Reading(false, 210.5)
    T.eq(env.ft:GetState(), "idle")
    T.eq(save.flight, nil)
end)

T.test("a pick while resuming wins over the saved flight", function()
    local save = { flight = { route = R1, takeoff = 2, elapsed = 28, recordable = true } }
    local env = make(save)
    env.ft:OnLoad(100, true)
    env.ft:Pick(R3, 101, 1)
    T.eq(env.ft:GetState(), "pending")
    T.eq(save.flight, nil)
end)

T.test("logout keeps the save while resuming and clears it while idle", function()
    local save = { flight = { route = R1, takeoff = 2, elapsed = 28, recordable = true } }
    local env = make(save)
    env.ft:OnLoad(100, true)
    env.ft:OnUnload(101)
    T.truthy(save.flight, "kept while resuming")
    local idle = loaded({ flight = nil })
    idle.save.flight = { stale = true }
    idle.ft:OnUnload(5)
    T.eq(idle.save.flight, nil)
end)

T.test("a malformed saved flight is dropped", function()
    local save = { flight = { takeoff = "x" } }
    local env = make(save)
    T.truthy(env.ft.droppedSave)
    T.eq(save.flight, nil)
end)
